name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Create Build Directory
      run: mkdir -p src/build

    - name: Configure CMake
      run: |
        cd src/build
        cmake ..

    - name: Build
      run: |
        cd src/build
        make

    - name: Run Tests
      run: |
        cd src/build
        make check

    - name: Run Distribution Check
      run: |
        cd src/build
        make distcheck
