name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Checkout repository
    uses: actions/checkout@v4
    with:
      submodules: true
    - name: configure
      run: cd src && mkdir build && cd build
    - name: Configure CMake
      run: |
        cd src
        mkdir -p build
        cd build
        cmake ..
    - name: make
      run: cd src/build && make
    - name: make check
      run: cd src/build && make check
    - name: make distcheck
      run: cd src/build && make distcheck
